repos:
  - repo: local
    hooks:
    - id: cargo-format
      name: cargo format
      description: Format files with cargo format
      entry: cargo fmt
      language: system
      types:
        - rust
      args:
        - "--"
      pass_filenames: false
    - id: cargo-check
      name: cargo check
      description: Run cargo check
      entry: cargo check
      language: system
      pass_filenames: false
      types:
        - rust
      args:
        - "--"
    - id: cargo-clippy
      name: cargo clippy
      description: Runs cargo clippy
      entry: cargo clippy
      language: system
      pass_filenames: false
      types:
        - rust
      args:
        - "--"
        - "-D warnings"
