repos:
  - repo: local
    hooks:
    - id: cargo-fmt
      name: cargo fmt
      description: Run cargo fmt
      entry: cargo fmt
      language: system
      pass_filenames: false
      types:
        - rust
      args:
        - "--"
    - id: cargo-clippy
      name: cargo clippy
      description: Runs cargo clippy
      entry: cargo clippy
      language: system
      pass_filenames: false
      types:
        - rust
      args:
        - "--"
        - "-D"
        - "warnings"
